export type NationStatus = 'available' | 'coming-soon';

export interface NationInfo {
  id: string;
  name: string;
  fullName: string;
  status: NationStatus;
  passportImage: string;
}

export const NATIONS: NationInfo[] = [
  {
    id: 'fsm',
    name: 'FSM',
    fullName: 'Federated States of Micronesia',
    status: 'available',
    passportImage: '/passport-fsm.webp',
  },
  {
    id: 'rmi',
    name: 'RMI',
    fullName: 'Republic of the Marshall Islands',
    status: 'coming-soon',
    passportImage: '/passport-rmi.png',
  },
  {
    id: 'palau',
    name: 'Palau',
    fullName: 'Republic of Palau',
    status: 'coming-soon',
    passportImage: '/passport-palau.png',
  },
];

export const FSM_PASSPORT_INFO = {
  requirements: [
    'Completed Form 500B (generated by this app)',
    'Two recent passport-sized photos (2" x 2")',
    'Certified copy of birth certificate',
    'Valid government-issued ID',
    'Previous passport (if renewing)',
  ],
  fees: [
    { label: 'Standard processing', amount: '$50.00' },
    { label: 'Expedited processing', amount: '$80.00' },
  ],
  processingTime: [
    { label: 'Standard', duration: '6-8 weeks' },
    { label: 'Expedited', duration: '2-3 weeks' },
  ],
  offices: [
    {
      name: 'Palikir, Pohnpei (National Government)',
      address: 'Department of Foreign Affairs, P.O. Box PS-123, Palikir, Pohnpei FM 96941',
    },
    {
      name: 'FSM Embassy, Washington D.C.',
      address: '1725 N Street NW, Washington, DC 20036',
    },
    {
      name: 'FSM Consulate, Honolulu',
      address: '900 Fort Street Mall, Suite 725, Honolulu, HI 96813',
    },
    {
      name: 'FSM Consulate, Guam',
      address: 'Suite 905 DNA Building, 238 Archbishop Flores St., Hagatna, Guam 96910',
    },
  ],
};
